# Generated by Django 4.2.7 on 2023-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('work_phone', models.CharField(max_length=200)),
                ('publish', models.BooleanField()),
            ],
        ),
    ]
