# Generated by Django 4.2.7 on 2023-12-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
