# Generated by Django 4.2.7 on 2024-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('cultural_counselor_office', 'Cultural Counselor’s Office'), ('cultural_attache_office', 'Cultural Attache’s Office'), ('accounting', 'Accounting'), ('administration', 'Administration'), ('placement', 'Placement'), ('graduate', 'Graduate'), ('undergraduate', 'Undergraduate'), ('translation', 'Translation'), ('information_technology', 'Information Technology')], max_length=200),
        ),
    ]
