# Generated by Django 4.2.7 on 2024-01-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='info_page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
