# Generated by Django 4.2.7 on 2024-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_info_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_photo',
            field=models.ImageField(blank=True, null=True, upload_to='diplomat_images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('cultural_counselor_office', 'Cultural Counselor’s Office'), ('cultural_attache_office', 'Cultural Attache’s Office'), ('accounting', 'Accounting'), ('administration', 'Administration'), ('placement', 'Placement'), ('program_eval', 'Program Evaluation'), ('graduate', 'Graduate'), ('undergraduate', 'Undergraduate'), ('translation', 'Translation'), ('information_technology', 'Information Technology')], max_length=200),
        ),
    ]
