# Generated by Django 4.2.7 on 2024-04-05 14:44

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('body', tinymce.models.HTMLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/imgs/')),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements/docs/')),
                ('publish', models.BooleanField(default=True)),
                ('important', models.BooleanField()),
                ('homepage_headline', models.BooleanField()),
            ],
        ),
    ]
