# Generated by Django 4.2.7 on 2024-01-10 15:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
