# Generated by Django 4.2.7 on 2024-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
