# Generated by Django 4.2.7 on 2024-01-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
