# Generated by Django 4.2.7 on 2024-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(default='', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents')),
            ],
        ),
    ]
