# Generated by Django 4.2.7 on 2024-02-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
