# Generated by Django 4.2.7 on 2024-02-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_document_important_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
    ]
