# Generated by Django 4.2.7 on 2024-01-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
