# Generated by Django 4.2.7 on 2024-01-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_page', '0002_page_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
