# Generated by Django 4.2.7 on 2024-01-11 15:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_page', '0003_page_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='html_body',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
