# Generated by Django 4.2.7 on 2024-01-11 19:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_page', '0004_page_html_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_body',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
