# Generated by Django 4.2.7 on 2024-01-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_page', '0005_page_page_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='body',
        ),
        migrations.RemoveField(
            model_name='page',
            name='html_body',
        ),
    ]
