# Generated by Django 4.2.7 on 2024-01-08 14:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('post_date', models.DateField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.FileField(upload_to='announcement_imgs/')),
                ('document_file', models.FileField(upload_to='announcement_docs/')),
                ('publish', models.BooleanField(default=True)),
                ('homepage_headline', models.BooleanField()),
                ('important_announce', models.BooleanField()),
                ('author', models.TextField(max_length=255)),
            ],
        ),
    ]
