# Generated by Django 4.2.7 on 2023-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_link',
            field=models.URLField(default='javascript:;', max_length=500),
        ),
    ]
