# Generated by Django 4.2.7 on 2023-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_card_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_visible',
            field=models.BooleanField(default=True),
        ),
    ]
