# Generated by Django 4.2.7 on 2023-12-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_card_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sponsor_page',
        ),
        migrations.AddField(
            model_name='card',
            name='page',
            field=models.CharField(default='home', max_length=120),
        ),
        migrations.AddField(
            model_name='card',
            name='sponsor',
            field=models.CharField(choices=[('mohe', 'Mohe'), ('kuwait university', 'Kuwait University'), ('civil service', 'Civil Service'), ('paaet', 'Paaet'), ('kuwait investment authority', 'Kuwait Investment Authority')], max_length=120, null=True),
        ),
    ]
