# Generated by Django 4.2.7 on 2023-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('rules', 'Rules'), ('requirements', 'Requirements')], max_length=120, null=True),
        ),
    ]
