# Generated by Django 4.2.7 on 2023-12-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_link',
            field=models.CharField(default='javascript:;', max_length=500),
        ),
    ]
