# Generated by Django 4.2.7 on 2024-01-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_card_card_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sponsor',
            field=models.CharField(choices=[('mohe', 'MOHE'), ('kuwait university', 'Kuwait University'), ('civil service', 'Civil Service'), ('paaet', 'PAAET'), ('kuwait investment authority', 'Kuwait Investment Authority')], max_length=120, null=True),
        ),
    ]
