# Generated by Django 4.2.7 on 2024-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('students', 'Students'), ('rules', 'Rules'), ('requirements', 'Requirements')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sponsor',
            field=models.CharField(choices=[('mohe', 'MOHE'), ('kuwait university', 'Kuwait University'), ('civil service', 'Civil Service'), ('paaet', 'PAAET'), ('kuwait investment authority', 'Kuwait Investment Authority'), ('all', 'All')], max_length=120, null=True),
        ),
    ]
