# Generated by Django 4.2.7 on 2024-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_card_page_alter_card_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='card_images'),
        ),
        migrations.AlterField(
            model_name='card',
            name='page',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('home', 'Home'), ('students', 'Students'), ('rules', 'Rules'), ('requirements', 'Requirements')], max_length=120, null=True),
        ),
    ]
